### PR TITLE
React rewrite + Custom palettes

### PR DESCRIPTION
**Pull request by Brendonovich**
Yeet custom palette time

### CODE REVIEW

**Comment by mat1jaczyyy** [comment]
Again I'm JS noob but isnt +6000 -2000 too large of a change?

**Comment by mat1jaczyyy** [comment]
I don't know how finished this is, but a couple suggestions:

* Make sure the velocity index we're currently editing is displayed somewhere
* You should hide the upload button if CFW is used instead of giving an error message
* Exporting a file exports with extension `.retina`, although retina files don't have an extension
* The current main screen design works well with CFW, but if anything else is selected: instead of a Palette Utility button at the bottom, it should be positioned between the dropdown and update button (maybe with a checkmark?)
* Palette being applied view could be smaller? It seems too wide compared to the rest of the page

**Comment by vaaski** [comment]
i prefer vue.js

**Comment by Brendonovich** [comment]
@vaaski make palette editor in vue and then sure

@mat1jaczyyy

- The velocity being edited has a white border
- Oke
- Oke
- I'll take a look
- Fair call

**Comment by mat1jaczyyy** [comment]
I know the selected velocity has a border, but it's still not known what index it is (display the numeric value 1 - 127 somewhere)

**Pull request merged**
